### ISSUE TITLE
Jwts 

### ISSUE THREAD

**Issue by cschneider** [jwtk/jjwt#600] opened 2020-06-09 07:24 UTC
The Jwts class uses  Classes.newInstance(<classname>) to load implementation classes. This is fundamentally broken when there is not a flat class loader. Generally I propose to never load classes from class names.

One example where this fails is OSGi. I have seen that there is a commit on master to attach impl bundles to the api bundle as fragments. This might work but it is a bad hack. The proper way would be to provide an initialization that does not depend on classloading hacks. 

I plan to propose a better way for this initialization.

See:
https://github.com/jwtk/jjwt/blob/master/api/src/main/java/io/jsonwebtoken/Jwts.java

**Comment by cschneider** [comment] 2020-06-09 12:17
The methods in Jwts seem to be largely around initializing classes from impl. Would it make sense to put the Jwts class into impl? This way it could directly access the impl classes without classloader magic. It could still live in a package outside of impl to signal that it is meant to be accessed by users.

**Comment by lhazlewood** [comment] 2020-06-09 16:51
This is by design: https://github.com/jwtk/jjwt#install-understandingdependencies

This helps ensure that developers only depend on classes they are 'allowed' to depend upon.  Moving `Jwts` to the `impl` module would force a project compile-time dependency on the `impl` package which is opposite of the design intentions.

FWIW, the `Classes` method implementations check the following classloaders in order, which should cover everything:

1. Thread context classloader
2. Current class classloader
3. System classloader

example: https://github.com/jwtk/jjwt/blob/master/api/src/main/java/io/jsonwebtoken/lang/Classes.java#L74-L82

Even though the OSGi 'hack' is in place, it works.  Given that OSGi appears to be a small subset of JJWT's user base, and that the hack works, it isn't clear to me that a change should be made.

That said, I'm totally open to any solution that you might be able to suggest that does not require a compile-time dependency on the `impl` .jar.  Does any come to mind?

**Comment by cziegeler** [comment] 2020-06-10 09:34
I don't care that much how it is done, as long as it works with OSGi - which it does now with the "hack" (and hack is probably a too strong word - its a consequenc of how this library is doing classloading). I personally would try to avoid loading classes by name - but I'm sure there are good reasons for this case - especially as it changed last year to this approach

**Comment by lhazlewood** [comment] 2020-06-11 17:50
Closing as I'm in the process of releasing 0.11.2 now.

**Closed by lhazlewood** 2020-06-11 17:50 UTC
