### ISSUE TITLE
Reflection operation problems: OptionalMethodInvoker cannot access KeyUtil(in module java.base) in java17 environment

### ISSUE THREAD

**Issue by win-ho** [jwtk/jjwt#851] opened 2023-10-04 16:06 UTC
I just got a error message from my program as below: 
"Reflection operation failed. This is likely due to an internal implementation programming error.  Please report this to the JJWT development team.  Cause: class io.jsonwebtoken.impl.lang.OptionalMethodInvoker cannot access class sun.security.util.KeyUtil (in module java.base) because module java.base does not export sun.security.util to unnamed module @4812a2ca".
My dev environment: java17 + springboot3 + jjwt 0.12.0.

**Comment by bdemers** [comment] 2023-10-04 16:16
We are looking into fixing this in the next release, for now you can the following to work around the issue:

```
--add-opens=java.base/sun.security.util=ALL-UNNAMED
```

**Comment by lhazlewood** [comment] 2023-10-04 16:21
Just a note: so we don't have 'me too' issues and comments, I'll be closing this in favor of #849 since this is a duplicate of the same underlying issue.

**Closed by lhazlewood** 2023-10-04 16:21 UTC

**Comment by lhazlewood** [comment] 2023-10-05 03:11
@win-ho this issue has been resolved and released in [0.12.1](https://github.com/jwtk/jjwt/releases/tag/0.12.1).  Please allow 30 minutes from the time of this post for the release to be in Maven Central.  Thank you for reporting the issue!

**Comment by lhazlewood** [comment] 2023-10-06 06:03
Just a note: the reflection code using `KeyUtil` has been removed in the [0.12.2](https://github.com/jwtk/jjwt/releases/tag/0.12.2) release in favor of a JJWT-native implementation to avoid JPMS scope issues entirely.  You shouldn't need `--add-opens` now (at least not for JJWT)
