### ISSUE TITLE
Add overloads to setExpiration and setIssuedAt

### ISSUE THREAD

**Issue by Aleksander-Dorkov** [jwtk/jjwt#801] opened 2023-08-24 10:05 UTC
Hello, do you have the time to add overloads to the methods `setExpiration `and `setIssuedAt` of `Jwts.builder()` that accept  `LocalDateTime` instead of the Date class, witch was kind of deprecated (not rly, but almost) 10 years go.

```
        Instant now = Instant.now();
        JwtBuilder jwtBuilder = Jwts.builder()
                .setId(UUID.randomUUID().toString())
                .setSubject(userDetails.getId().toString())
                .claim("username", userDetails.getUsername())
                .claim("authorities", authorities)
                .setIssuedAt(Date.from(now))
                .setExpiration(Date.from(now.plus(1, ChronoUnit.DAYS)))
                .signWith(KEY);
```
Instead of the code above can we have

```
        JwtBuilder jwtBuilder = Jwts.builder()
                .setId(UUID.randomUUID().toString())
                .setSubject(userDetails.getId().toString())
                .claim("username", userDetails.getUsername())
                .claim("authorities", authorities)
                .setIssuedAt(LocalDateTime.now())
                .setExpiration(LocalDateTime.now().plus(1, ChronoUnit.DAYS))
                .signWith(KEY);

```

It should  be fairly simple, because you just convert them to a unix timestamp, if I am not mistaking.

**Comment by lhazlewood** [comment] 2023-08-24 17:56
Closing as duplicate of #662

**Closed by lhazlewood** 2023-08-24 17:56 UTC
