### ISSUE TITLE
Obtain claim as POJO

### ISSUE THREAD

**Issue by kag0** [jwtk/jjwt#168] opened 2016-09-13 19:30 UTC
Currently `DefaultClaims.get(String, Class)` does a bit of date foo or casts the value removed from the claim map. It would be great if the claims object retained the original JSON (perhaps an internal `Map<String, JsonNode>`) and used jackson to deserialize it into the passed class. This might be useful when a claim value is an object, or alternative json types (like `BigDecimal`), or to allow extensions into things jjwt doesn't support (like java 8 `Optional`).

Does this seem like a valid feature candidate?

**Comment by lhazlewood** [comment] 2016-09-14 16:02
Hrm - what might this look like?  My personal preference is typically in favor of simplicity.

i.e. while not perfect, serializing your object to a string and then saving that as a claim is pretty trivial these days - I'd want to ensure that whatever we supported natively didn't add so much complexity (and still not work for a decent number of cases) when this alternative will always work.  Thoughts?

**Comment by kag0** [comment] 2016-09-14 17:31
So I'd propose adding another method, `JsonNode getJson(String)` to retrieve the original JSON value of a claim field. This way all manner of mapping can be covered by the user without adding to jjwt.  
The existing `get(String, Class)` method could be modified to look something like this
```java
public <T> T get(String claimName, Class<T> requiredType) {
  Object value = get(claimName);
  if (value == null) { return null; }

  if (Claims.EXPIRATION.equals(claimName) ||
    Claims.ISSUED_AT.equals(claimName) ||
    Claims.NOT_BEFORE.equals(claimName)
  ) {
    value = getDate(claimName);
  }

  if (requiredType == Date.class && value instanceof Long) {
    value = new Date((Long)value);
  }

  if (!requiredType.isInstance(value)) {
    try{
      return mapper.treeToValue(getJson(claimName), requiredType);
    }catch(JsonProcessingException e){
      throw new RequiredTypeException("Expected value to be of type: " + requiredType + ", but was " + value.getClass());
    }
  }

  return requiredType.cast(value);
}
```  
This could be implemented by adding a field `Map<String, JsonNode> json` to `JwtMap` or `DefaultClaims`. `getJson(String)` would then simply return values from `json`.

This addition to `get(String, Class)` doesn't change any existing use cases, but gives one more chance to return without exception. `getJson(String)` then covers the rest of cases where the user has complex mapping and needs to use their own mapper.  
While serializing an object to a string and putting that in the claim is easily supported most places, not all JWTs a user could receive will be issued by them. For example, OpenID Connect specifies `address` as a standard claim, which is an object. If I wanted to build an OpenID Connect library on jjwt, I'd probably want to turn that into an `AddressClaim` pojo (of course I could get it as a map and map that map to my pojo, but I think most would rather just work with the json).

What do you think?

**Comment by cbudtz** [comment] 2017-03-14 13:41
Great Idea - was just about to propose the same. This is what I'm doing though:
		 return mapper.convertValue(value, User.class);

**Comment by eonezhang** [comment] 2018-08-23 02:31
no update yet?

**Comment by lhazlewood** [comment] 2018-08-23 15:36
Because Object unmarshalling can be very complex (type discovery, optional vs required properties, etc), this is not something that we want support directly in the JwtParser API itself - JWT parsing and RFC compliance and POJO unmarshalling are totally separate concerns and should ideally not be tightly coupled.   This opinion is reinforced by the fact that some JSON libraries (like org.json in Android and others) don't even support JSON unmarshalling - which implies it definitely can't be native in the JwtParser interface itself.  Doing so would force all JSON implementations to support unmarshalling, or for JJWT itself to write unmarshalling logic for supported JSON libraries that don't - which is definitely a non-trivial amount of work(!) and really outside the scope of JJWT as an RFC-compliant library.

Instead, the 0.10 release made it easy to configure your own Deserializer to perform unmarshalling if you desire (e.g. delegate to Jackson) so that the object is unmarshalled *before* JJWT starts to inspect the JSON Map to construct the Jwt object instance (see the existing `JacksonDeserializer` for a starting point if you want to make your own implementation).

The effort to make JacksonDeserializer easily configurable for this type of unmarshalling (so you don't have to create your own Deserializer implementation) is being tracked in #369 and will be in the next minor release.

So this issue (168) is sort of a duplicate of, and superceded by, the newer #369 issue as the implementation approach.  I hope that helps!

**Comment by lhazlewood** [comment] 2019-03-10 17:38
Closing this as a duplicate of #369.

**Closed by lhazlewood** 2019-03-10 17:38 UTC
