### ISSUE TITLE
The signing key's algorithm 'HMACSHA256' does not equal a valid HmacSHA* algorithm name and cannot be used with HS256.

### ISSUE THREAD

**Issue by ITWall** [jwtk/jjwt#385] opened 2018-08-14 02:40 UTC
This error occured when I run the sample in readme. After check the SignatureAlgorithm.java file, I found out that the HS256.jcaName = HmacSHA256 but the secretKey.getAlgorithm() = HMACSHA256 so it will return false when you use equals to compare them and throw the error. You can check it at line 352 of SignatureAlgorithm.java file. Please fix it soon! Thank you.

**Comment by lhazlewood** [comment] 2018-08-14 02:58
Duplicate of #381.  This has been fixed and released in 0.10.3

**Closed by lhazlewood** 2018-08-14 02:58 UTC

**Comment by ITWall** [comment] 2018-08-14 06:53
I still got the error when I use 0.10.3 version on android

**Comment by lhazlewood** [comment] 2018-08-14 15:00
Yep, I've re-opened 381 - we'll get a fix out in 0.10.4 today.  Thanks for reporting this!
