### ISSUE TITLE
Native memory leak - GZIPInputStream is not closed

### ISSUE THREAD

**Issue by csegedicsaba** [jwtk/jjwt#949] opened 2024-06-16 22:19 UTC
Using jwt token with GZIP compression cause native (not heap) memory leak because the GZIPInputStream is not closed.

After large number of decompressing cca. 500 MB of extra memory is used by the java process. This extra usage can see in /proc/1/status only. The java native memory tracking will not show it.

Running application in kubernetes will result kubernetes level OOM because this extra memory usage when memory limit is set.

Hacking GzipCompressionAlgorithm.**doDecompress**(InputStream is) like this there is no memory leak:
``` 
protected InputStream doDecompress(InputStream is) throws IOException {
    GZIPInputStream gzipIs = new GZIPInputStream(is);
    byte[] tmpIs = gzipIs.readAllBytes();
    gzipIs.close();
    return Streams.of(tmpIs);
}
```

**Comment by lhazlewood** [comment] 2024-06-16 22:29
Thanks for the report!  We'll fix this, but note: GZIP is not a compression algorithm defined by the JWT RFCs ([only DEFLATE is defined](https://www.rfc-editor.org/rfc/rfc7518.html#section-7.3.2)), so only use GZIP if both the JWT issuer and consumer support it.

**Comment by lhazlewood** [comment] 2024-06-16 22:32
Also, have you confirmed this is always solved by your fix? 

I ask because the stream shouldn't be copied to memory in its entirety - that defeats the purpose of the stream.  The consumer of the opened stream should close it, and those usages are usually wrapped in `finally` blocks to ensure it's always closed.

Do you have a test case that demonstrates the behavior without using the intermediate hack?

**Comment by csegedicsaba** [comment] 2024-06-16 22:52
This was quick and dirty solution to make sure closing the stream will solve the issue.
I hope the final solution will be more professional :-)

Create a jwt token with GZIP compression, decompress 10.000.000 times. 
With jcmd run a gc and check the memory usage with jcmd and in /proc/1/status.
I tested in docker.

**Comment by lhazlewood** [comment] 2024-06-16 22:57
Thanks for the suggestion - do you have a docker container to share for quick testing? It'd be much easier than starting from scratch for us.

**Comment by lhazlewood** [comment] 2024-06-16 23:02
@csegedicsaba please see https://github.com/jwtk/jjwt/pull/950 for the fix. The only difference is the changed code is now wrapped in a try/finall block that closes the InputStream.  If you can test it, please do.  I still have testing to do on my end, but I wanted to make it available for you just in case.

**Comment by csegedicsaba** [comment] 2024-06-16 23:42
Thx @lhazlewood!
There is no memory leak with this fix.

**Comment by lhazlewood** [comment] 2024-06-17 00:20
Thanks for confirming!  I was not able to replicate the problem in my docker environment using only 256 mb allocated to the container with 10 million decompression attempts using the following test in the project directory on my local machine:

> docker run -it --memory=256m --rm -v "$PWD":/build -v "$HOME/.m2":/root/.m2 -v "$PWD/target:/usr/src/mymaven/target" -w /build maven mvn test -pl impl -Dtest=JwtsTest#testIssue949

where `JwtsTest#testIssue949` is this:

```groovy
    @Test
    void testIssue949() {
        def alg = Jwts.SIG.HS256
        SecretKey key = TestKeys.HS256

        String id = UUID.randomUUID().toString()

        String compact = Jwts.builder().id(id).issuer("an issuer").signWith(key, alg)
                .claim("state", "hello this is an amazing jwt").compressWith(Jwts.ZIP.GZIP).compact()

        def parser = Jwts.parser().verifyWith(key).build()
        for (int i = 0; i < 10_000_000; i++) {
            if (i % 50000 == 0) {
                println "Decompressed ${i} times"
            }
            parser.parseSignedClaims(compact)
        }
    }
```

If you have a better test, please let me know and I'll try it locally.

**Comment by csegedicsaba** [comment] 2024-06-17 05:45
@lhazlewood here is a project for testing: https://github.com/csegedicsaba/jjwt-memory-leak-poc
I see that there is only memory leak when using multiple threads.

**Comment by lhazlewood** [comment] 2024-06-17 18:45
@csegedicsaba thank you so much for this, it's so helpful!  Also, I don't know what happened to my previous (now-deleted) comment, but this test project will definitely help.  I'll be able to merge the fix shortly.  Cheers! 🥂

**Closed** 2024-06-17 19:25 UTC

**Comment by csegedicsaba** [comment] 2024-06-17 19:27
There is no `OutOfMemoryException` because the memory leak is not inside the memory managed by jvm.
From this reason is very hard to identify this issue.

I think the best way to test is to run **without** and **with** the fix and check the whole memory usage with 'docker stats poc'.

**Comment by lhazlewood** [comment] 2024-06-17 19:29
Yes, that's what I did and noticed the memory differences, but I was curious how an application developer or infrastructure engineer might see this surface in a production application.

**Comment by csegedicsaba** [comment] 2024-06-21 07:27
When will the next version (0.12.6) be released?

**Comment by lhazlewood** [comment] 2024-06-21 18:38
@csegedicsaba I can probably try to get it out asap, there's likely no need to delay for additional features/fixes.  Those could always go into a 0.12.7 release if necessary.
