### ISSUE TITLE
Unable to parse JWT created from JavaScript

### ISSUE THREAD

**Issue by gamedevhelper** [jwtk/jjwt#91] opened 2016-02-07 01:00 UTC
I created a demo signed JWT using Javascript with the key "demo". When I send this signed 256 or 512 JWT to back end that uses jjwt, I am getting exception 
*"io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT validity cannot be asserted and should not be trusted".*  I re-verified that I am using the same key "demo" when parsing it in the back end. 

Is this because jjwt doesn't support Non-compact serialization and parsing ? Or there some other issues?

FYI I am using http://codepen.io/jpetitcolas/pen/zxGxKN from http://www.jonathan-petitcolas.com/2014/11/27/creating-json-web-token-in-javascript.html

**Comment by lhazlewood** [comment] 2016-02-07 02:52
Cryptographic signatures are always computed with keys that are byte arrays, not strings.  If you supply a string as the key to JJWT, it assumes the string is a base64-encoded byte array and JJWT will base64-decode the string first to get the actual key bytes.

In your case, I suspect that if you called `"demo".getBytes("UTF-8")` and passed those bytes to JJWT as the key, it would work.  **However**: this is not a safe key to use for SHA-256 or SHA-512 - it is not long enough for those algorithms and susceptible to collision attacks.

If you want to use a safe key, see the `MacProvider.generateKey()` or `MacProvider.generateKey(SignatureAlgorithm alg)` JavaDoc.

**Comment by gamedevhelper** [comment] 2016-02-07 08:21
I generated a new key using MacProvider.generateKey().  I also switch to another more mainstream JavaScript Library http://kjur.github.io/jsjws/tool_jwt.html and created new token with the the new generated key.  However result is still same. *Untrusted token JWT signature does not match locally computed signature*

**Comment by lhazlewood** [comment] 2016-02-08 17:03
We don't know how they implement the specification, and unfortunately we don't have the time to track down discrepancies with other projects.  I will say that JWTs created JJWT are interoperable with other JavaScript libraries we've seen, so the problem is probably with the library/libraries you've tried.  Without further information on why you're seeing problems or a test project that demonstrates a problem, we can't do much.

**Comment by lhazlewood** [comment] 2016-02-08 17:13
I just thought of something:  MacProvider.generateKey() returns a byte array.  Are you base64 encoding this before providing it to the JavaScript library?  If so, does that library know how to use base64 strings?  I've seen many JavaScript libraries incorrectly deal with key strings...

**Comment by lhazlewood** [comment] 2016-04-01 23:24
Given no follow ups by the OP, I'm closing this issue.  Please feel free to re-open if you can provide a test case that shows what is breaking.

**Closed by lhazlewood** 2016-04-01 23:24 UTC

**Comment by hisankaran** [comment] 2016-04-07 03:40
I am using https://www.npmjs.com/package/jsonwebtoken and I had the same problem 
> In your case, I suspect that if you called `"my_secret_key".getBytes("UTF-8")` and passed those bytes to JJWT as the key, it would work.

This helped me to safely decode the body.

**Comment by lhazlewood** [comment] 2016-04-07 15:35
I personally don't trust most JavaScript-based solutions - of the ones I've seen, they have had silly cryptography mistakes and as a result haven't been that trustworthy in my opinion.  Because JJWT was written and verified with test cases that came directly from the RFC, it is as 'correct' as I've seen.

@hisankaran - I don't know your exact use case, but "my_secret_key".getBytes("UTF-8") is almost never a good idea.  That gets the bytes of the characters in the key string itself.  The best symmetric signing keys are secure, randomly-generated byte arrays that are then Base64 encoded.  For these, you shouldn't get the Base64 String's bytes - you need to Base64 decode that string first and take the resulting bytes from that.  In other words:

Bad:

```java
byte[] key = "mykey".getBytes("UTF-8");
```

Good:

```java
byte[] key = Base64.decode("myBase64EncodedKey");
```

It is *not* ok to just make up a private password and use that.  It is really important to ensure your key has enough entropy (secure random) and a byte length long enough for the signature algorithm you're using.

This is why `MacProvider.generateKey()` and `generateKeyPair(SignatureAlgorithm)` exist - to ensure that you start with a secure random key, but not just that - it ensures your key _length_ is long enough for your desired signature algorithm to ensure it is less susceptible to attack.

**Comment by jieliu218** [comment] 2018-07-13 22:22
@gamedevhelper 

Hi, have you solved this problem?

**Comment by jieliu218** [comment] 2018-07-13 22:40
@hisankaran Hi, have you solved this problem?, which front end lib do you use?

**Comment by hisankaran** [comment] 2018-07-14 05:00
@jieliu218 I am using this lib on my android app.

**Comment by hisankaran** [comment] 2018-07-14 14:00
May be post your decoding snippit and error details. I can help you.

**Comment by jieliu218** [comment] 2018-07-27 18:59
@hisankaran thanks， i change another two libs。 working well
