### ISSUE TITLE
I have error in DefaultJwsHeader class of Name Clash  

### ISSUE THREAD

**Issue by MohamedHaggagH** [jwtk/jjwt#124] opened 2016-05-20 13:34 UTC
Multiple markers at this line
	- Name clash: The method compute(K, BiFunction<? super K,? super V,? extends V>) of type Map<K,V> has the same erasure as 
	 compute(K, BiFunction<? super K,? super V,? extends V>) of type Map<K,V> but does not override it
	- Name clash: The method computeIfAbsent(K, Function<? super K,? extends V>) of type Map<K,V> has the same erasure as 
	 computeIfAbsent(K, Function<? super K,? extends V>) of type Map<K,V> but does not override it
	- Name clash: The method merge(K, V, BiFunction<? super V,? super V,? extends V>) of type Map<K,V> has the same erasure as 
	 merge(K, V, BiFunction<? super V,? super V,? extends V>) of type Map<K,V> but does not override it
	- Name clash: The method replace(K, V, V) of type Map<K,V> has the same erasure as replace(K, V, V) of type Map<K,V> but 
	 does not override it
	- Name clash: The method replace(K, V) of type Map<K,V> has the same erasure as replace(K, V) of type Map<K,V> but does 
	 not override it
	- Name clash: The method computeIfPresent(K, BiFunction<? super K,? super V,? extends V>) of type Map<K,V> has the same 
	 erasure as computeIfPresent(K, BiFunction<? super K,? super V,? extends V>) of type Map<K,V> but does not override it
	- DefaultHeader is a raw type. References to generic type DefaultHeader<T> should be parameterized
	- JwsHeader is a raw type. References to generic type JwsHeader<T> should be parameterized
	- The default method replaceAll(BiFunction<? super String,? super Object,? extends Object>) inherited from 
	 Map<String,Object> conflicts with another method inherited from Map<String,Object>
	- Name clash: The method putIfAbsent(K, V) of type Map<K,V> has the same erasure as putIfAbsent(K, V) of type Map<K,V> 
	 but does not override it
	- The default method forEach(BiConsumer<? super String,? super Object>) inherited from Map<String,Object> conflicts with 
	 another method inherited from Map<String,Object>

**Comment by lhazlewood** [comment] 2016-05-20 15:01
Which version of Java are you using?

JJWT builds on Oracle JDK  7 and JDK 8:

https://travis-ci.org/jwtk/jjwt

**Comment by MohamedHaggagH** [comment] 2016-05-22 08:28
First of all thank you for your fast reply,
I am  using JDK 8. I  removed the implementation of jwsHeadr interface from DefaultJwsHeader and it Worked jusy fine.

Thank you for this amazing library :).

**Comment by lhazlewood** [comment] 2016-05-22 18:32
Hi - thanks for the feedback!  Which JDK 8?  Oracle JDK 8? Or Open JDK 8?

I'm confused as to why it builds on Oracle JDK 8 in TravisCI but fails on your JDK 8.

**Comment by MohamedHaggagH** [comment] 2016-05-22 18:41
![screenshot from 2016-05-22 20 40 46](https://cloud.githubusercontent.com/assets/10831441/15455728/ecf061e4-2065-11e6-8e70-456f444e2f75.png)

**Comment by MohamedHaggagH** [comment] 2016-05-22 18:48
![screenshot from 2016-05-22 20 47 42](https://cloud.githubusercontent.com/assets/10831441/15455764/dcd17ce8-2066-11e6-90b4-11c9c07a2fb1.png)

**Comment by lhazlewood** [comment] 2016-05-22 18:50
Then I can't say why it fails for you.  Our CI server runs the build on JDK 8 and it passes with no problems.

Please try to build JJWT on the command line (using Maven) and not in an IDE.  If it passes on the command line and fails in your IDE, then the problem is with your IDE, not JJWT.

I hope that helps!

**Comment by MohamedHaggagH** [comment] 2016-05-22 19:12
Thank you,Unfortunately I don't know Maven but i will try to do it and give you the feedback.

**Comment by lhazlewood** [comment] 2016-06-07 20:37
I'm closing this issue as there does not appear to be a problem with JJWT itself.  Please re-open if you discover otherwise.  For general questions, please use StackOverflow and use the `jjwt` tag.  Thanks!

**Closed** 2016-09-11 20:51 UTC
