### ISSUE TITLE
Locator for Key has no access to JWT claims (issuer)

### ISSUE THREAD

**Issue by langbeinmovio** [jwtk/jjwt#886] opened 2024-01-08 05:00 UTC
The `SigningKeyResolver` is deprecated. Its replacement `Locator` has only access to the JWT header, not to the claims. We accept JWT tokens from various issuers, and the JWT claims contains the `issuer` field that we use to determine what signing key must be used to verify the token.

**Comment by lhazlewood** [comment] 2024-01-08 18:36
Hi @langbeinmovio !  This is a duplicate of #857.  Please read that thread in detail to understand why this change was made, particularly this https://github.com/jwtk/jjwt/issues/857#issuecomment-1789607255.

I'll be closing this as a duplicate, but feel free to discuss in the #857 thread if desired.  Thanks!

**Closed by lhazlewood** 2024-01-08 18:36 UTC
Labels: duplicate
