### ISSUE TITLE
jjwt setClaims problem

### ISSUE THREAD

**Issue by Joebig7** [jwtk/jjwt#703] opened 2022-01-20 15:46 UTC
Hello,i use jjwt to generate token like this:
```java

Jwts.builder()
        .setSubject((userPrincipal.getUsername()))
        .setIssuedAt(new Date())
       .setClaims(clams)
        .setExpiration(new Date((new Date()).getTime() + jwtExpirationMs))
        .signWith(SignatureAlgorithm.HS256, jwtSecret)
        .compact();
```
but in this order,Subject and issuedAt will be overrided by clams,because clams will be decalared again,so i have to setClaims first,like this:

```java

Jwts.builder()
       .setClaims(clams)
        .setSubject((userPrincipal.getUsername()))
        .setIssuedAt(new Date())
        .setExpiration(new Date((new Date()).getTime() + jwtExpirationMs))
        .signWith(SignatureAlgorithm.HS256, jwtSecret)
        .compact();
```

i think it can be improved to prevent it happening,pleanse check this thanks a lot

**Comment by bdemers** [comment] 2022-01-20 15:53
Duplicate of #702

**Closed by bdemers** 2022-01-20 15:53 UTC
