### ISSUE TITLE
Update to LocalDateTime instead of the old Date API

### ISSUE THREAD

**Issue by dstr89** [jwtk/jjwt#577] opened 2020-03-17 12:37 UTC
In my Unit tests I would like to use something like this to fix the time when validating JWT:

```
Instant.now(Clock.fixed(
                Instant.parse("2018-08-22T10:00:00Z"),
                ZoneOffset.UTC));
```
But this is not possible since JJWT uses the old date API. In DefaultClock now() method.

BR,
Daniel

**Comment by lhazlewood** [comment] 2020-03-17 17:40
Closing as a duplicate of #235 .  In the meantime, you'll need to convert the JDK 8+ time concepts into a `java.util.Date`.  HTH!

**Closed by lhazlewood** 2020-03-17 17:40 UTC
