### ISSUE TITLE
Way to get Claims from expired JWT

### ISSUE THREAD

**Issue by seunghx** [jwtk/jjwt#378] opened 2018-08-07 12:30 UTC
hi i'm student using jjwt to my project.

i need some information(claim) from expired jwt.

but JwtParset#parseClaimsJws() throws ExpiredJwtException immediately,
so i could not get some information. for example, user id ...

if expired access token detected, i want to check refresh token(or similar data) in DB but
since i could not get user id from expired jwt token(access token) due to ExpiredJwtException,
i can't check refresh token info(or similar data like expired time information) from DB.

though not mandatory, i think way to get data from expired JWT token is needed for 
implementation flexibility/diversity

thanks^^^^^^^^^

**Comment by lhazlewood** [comment] 2018-08-07 15:00
Duplicate of #148.  We'll try to address this as soon as we're able.  JWE is currently a higher priority.

The best way to do this is to set your own `Clock` instance on the parser.  Return a date that is in the future and the parsing will not fail.

**Closed by lhazlewood** 2018-08-07 15:00 UTC

**Comment by seunghx** [comment] 2018-08-07 17:00
Thanks a lot !

2018-08-08 0:00 GMT+09:00 Les Hazlewood <notifications@github.com>:
