### ISSUE TITLE
why use older java.util.Date?

### ISSUE THREAD

**Issue by ashcoll** [jwtk/jjwt#402] opened 2018-10-02 06:00 UTC
## jjwt-version: 0.10.5

```java
setIssuedAt(Date date)
setExpiration(Date date)
```

why not update to use `java.time.*` api?

**Comment by javapapo** [comment] 2018-10-12 09:22
+1

**Comment by lhazlewood** [comment] 2018-10-12 15:31
Duplicate of #308 Please see that issue for why we don't use `java.time` yet.  We will however!

**Closed by lhazlewood** 2018-10-12 15:31 UTC
