### ISSUE TITLE
[request] support for java.time

### ISSUE THREAD

**Issue by IARI** [jwtk/jjwt#667] opened 2021-06-19 09:53 UTC
I is my understanding that java.util.Date should not be used anymore.
I suggest to add support for java.time.

**Comment by bdemers** [comment] 2021-06-19 19:05
This will likely be added in v1. The current version of JJWT currently targets Java 7 APIs for Android compatibility (which is why we are still using Date)

I don’t know if I would say, ‘Date’ shouldn’t be used, but I would still much rather use Instant and Duration instead 😀

**Comment by lhazlewood** [comment] 2021-06-22 18:34
Internal note: see #308 and #352

**Comment by limbic-derek** [comment] 2022-02-06 18:38
Any updates on this? Seems like a smart API update to me.

**Comment by linghengqian** [comment] 2022-02-07 04:27
> Any updates on this? Seems like a smart API update to me. 

This should be one of the milestones of 1.0, and judging from the issue distribution 1.0 is still heavy work. At the same time, the 0.11.3 and 0.12.0 milestones still have unresolved issues.

**Comment by bdemers** [comment] 2022-02-07 15:14
@linghengqian the biggest thing in v1, is the JWE work, if you are interested in helping try it out, please take a look at the `jwe` branch 😄

**Comment by linghengqian** [comment] 2022-05-02 01:30
> @linghengqian the biggest thing in v1, is the JWE work, if you are interested in helping try it out, please take a look at the `jwe` branch 😄 

I feel do not know how to start, for the vast and corresponding PR look it at the end stage, but does not have an issue of what it needs other parts (if I do not understand the function of snoatype-lift wrong, refer to https://github.com/jwtk/jjwt/pull/279 ).

**Comment by lhazlewood** [comment] 2022-05-02 01:41
@linghengqian that's true - JWE is large and almost finished, so given the scope, it's probably best to leave the remaining work for JJWT team members.  Normally I feel otherwise (anyone should jump in!) but it's a daunting task for jwe to wrap up because it includes *so* much stuff, like JWK support, key management algorithms, AEAD encryption algorithms, and various interface cleanup additions.

**Comment by lhazlewood** [comment] 2023-08-11 22:00
Closing as duplicate of #235 so we can track this in one place

**Closed by lhazlewood** 2023-08-11 22:00 UTC
