### ISSUE TITLE
calling setClaims() after setSubject() will cause NullPointerException

### ISSUE THREAD

**Issue by pnrakesh** [jwtk/jjwt#179] opened 2016-10-14 10:16 UTC
Executing the below program will throw NullPointerException at line 38

**Code**

```
package foo.bar;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.SignatureAlgorithm;
import io.jsonwebtoken.impl.crypto.MacProvider;

import java.security.Key;
import java.util.HashMap;
import java.util.Map;

public class JWTTest {

    private static final Key key = MacProvider.generateKey();

    public static void main(String[] args) {
        JWTTest test = new JWTTest();
        test.verifyToken(test.generateToken());
    }

    String generateToken(){
        Map<String, Object> map = new HashMap<>();
        map.put("username", "someuser");
        map.put("password", "somepassword");
        String compactJws = Jwts.builder()
                .setSubject("Joe")
                .setClaims(map)
                .signWith(SignatureAlgorithm.HS512, key)
                .compact();
        System.out.println("generated token : "+compactJws);
        return compactJws;
    }

    void verifyToken(String token){
        Claims claims = Jwts.parser().setSigningKey(key).parseClaimsJws(token).getBody();
        System.out.println("username -> "+claims.get("username"));
        System.out.println("password -> "+claims.get("password"));
        System.out.println(claims.getSubject().equals("Joe"));
    }
}


```

**Output : **

```
generated token : eyJhbGciOiJIUzUxMiJ9.eyJ1c2VybmFtZSI6InNvbWV1c2VyIiwicGFzc3dvcmQiOiJzb21lcGFzc3dvcmQifQ.v2Um5SbAmCQwRqCHNYPhnsHHxjTRe8nnCDQVLZz5pi9l5PCF9GikXjJfi_bhR6641pnpfuHvozFeUrMvLb7AVA
username -> someuser
password -> somepassword
Exception in thread "main" java.lang.NullPointerException
	at foo.bar.JWTTest.verifyToken(JWTTest.java:38)
	at foo.bar.JWTTest.main(JWTTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
```

**Comment by dogeared** [comment] 2016-10-14 13:31
Hi @pnrakesh:

The `setClaims` method sets (or resets) the *entire* payload for the JWT. It replaces any previously set claims with the map passed in.

If you called `setClaims` first and then called `setSubject` your example would work as intended.

You're getting an NPE because there is no `sub` claim set in the resultant JWT.

Does that make sense?

I'm going to close this issue as the library is working as intended.

**Closed by dogeared** 2016-10-14 13:31 UTC

**Comment by pnrakesh** [comment] 2016-10-18 09:09
Thanks @dogeared !
