### ISSUE TITLE
Unable to find an implementation for interface io.jsonwebtoken.io.Serializer ... in fat jar

### ISSUE THREAD

**Issue by dimipaun** [jwtk/jjwt#573] opened 2020-03-11 12:56 UTC
Hi guys,

We are seeing this error:
`Unable to find an implementation for interface io.jsonwebtoken.io.Serializer using java.util.ServiceLoader. Ensure you include a backing implementation .jar in the classpath, for example, jjwt-impl.jar, or your own .jar for custom implementations.`

Of course, we've included all deps:
```
     implementation 'io.jsonwebtoken:jjwt-api:0.11.0'
     implementation 'io.jsonwebtoken:jjwt-impl:0.11.0'
     implementation 'io.jsonwebtoken:jjwt-gson:0.11.0'
```

We are using a fat jar (all jars merged into one big jar). I've checked and the classes are present in our fat jar:
```
$ jar tf releases/server-1.20.42.jar | grep jsonwebtoken.*Serializer
io/jsonwebtoken/io/JacksonSerializer.class
io/jsonwebtoken/gson/io/GsonSerializer.class
io/jsonwebtoken/io/Serializer.class
```

There's something I'm missing because this class is loaded using the standard [ServiceLoader](https://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html) which says:

> A service provider is identified by placing a provider-configuration file in the resource directory META-INF/services. The file's name is the fully-qualified binary name of the service's type. 

Well, I can see any such file in the jjwt-gson:
```
$ mkdir temp; cd temp
$ jar xf ~/.gradle/caches/modules-2/files-2.1/io.jsonwebtoken/jjwt-gson/0.11.0/8042478d4d0024aa4edb0d608475093acfc7f3e8/jjwt-gson-0.11.0.jar
$ find -type f
./io/jsonwebtoken/gson/io/GsonSerializer.class
./io/jsonwebtoken/gson/io/GsonDeserializer.class
./META-INF/MANIFEST.MF
./META-INF/maven/io.jsonwebtoken/jjwt-gson/pom.xml
./META-INF/maven/io.jsonwebtoken/jjwt-gson/pom.properties
```
So I'm not sure how this is supposed to work.

**Comment by lhazlewood** [comment] 2020-03-11 17:10
Duplicate of https://github.com/jwtk/jjwt/issues/563.  This will be out in the 0.11.1 bugfix release. Sorry!

**Closed by lhazlewood** 2020-03-11 17:10 UTC

**Comment by lhazlewood** [comment] 2020-03-11 17:57
P.S. Until 0.11.1 is released, you can use your own Gson Serializer/Deserializer instances manually as documented here:  https://github.com/jwtk/jjwt#json-gson

**Comment by masterdany88** [comment] 2020-06-04 18:04
Hi. I have same issue while working with war package.
I have jjwt-impl-0.11.1.jar and jjwt-api-0.11.1.jar inside
App-server-0.0.2-SNAPSHOT.war\WEB-INF\lib\
But tomcat prints error:
`
04-Jun-2020 19:55:53.156 SEVERE [http-nio-9000-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [com.qiagen.qbase.qbap.server.conf.RestConfig] in context with path [] threw exception [io.jsonwebtoken.lang.UnknownClassException: Unable to find an implementation for interface io.jsonwebtoken.io.Serializer using java.util.ServiceLoader. Ensure you include a backing implementation .jar in the classpath, for example jjwt-impl.jar, or your own .jar for custom implementations.] with root cause
	io.jsonwebtoken.impl.lang.UnavailableImplementationException: Unable to find an implementation for interface io.jsonwebtoken.io.Serializer using java.util.ServiceLoader. Ensure you include a backing implementation .jar in the classpath, for example jjwt-impl.jar, or your own .jar for custom implementations.
		at io.jsonwebtoken.impl.lang.Services.loadFirst(Services.java:105)
		at io.jsonwebtoken.impl.lang.LegacyServices.loadFirst(LegacyServices.java:21)
		at io.jsonwebtoken.impl.DefaultJwtBuilder.compact(DefaultJwtBuilder.java:300)
		at com.app.adapter.jwt.JwtAdapter.create(JwtAdapter.java:43)
`

**Comment by mbogner** [comment] 2020-10-29 22:06
With 0.11.2 I got the same error that impl couldn't be found. Adding the jackson lib as stated above solved that problem for me as well.

**Comment by watery** [comment] 2020-11-03 11:48
@mbogner Did you explicitly used `0.11.1` for that dependency while you're using jjwt `0.11.2`?
I'm using `0.11.2` for all the dependencies and I'm still seeing this.

**Comment by robbzzzzzzz** [comment] 2021-07-06 03:00
@masterdany88 I adopted this guy‘s guidance，now it works. A dependency is missing

**Comment by robbzzzzzzz** [comment] 2021-07-06 03:03
> @masterdany88 I adopted this guy‘s guidance，now it works. A dependency is missing

But before the program can run normally，When we upload a new version，report this error. thanks @masterdany88

**Comment by darioseidl** [comment] 2021-08-13 17:15
Is a serializer JAR (for Jackson or Gson) required?

Like @mbogner said, 

> With 0.11.2 I got the same error that impl couldn't be found. Adding the jackson lib as stated above solved that problem for me as well.

with 0.11.2 I'm also seeing this error unless I include the Jackson or Gson jar and the error message is misleading as it says that the `jjwt-impl.jar` is missing, but it's actually the `jjwt-jackson.jar` that was missing in my case:

```
    implementation("io.jsonwebtoken:jjwt-api:0.11.2")
    runtimeOnly("io.jsonwebtoken:jjwt-impl:0.11.2")
```

results in:

> Unable to find an implementation for interface io.jsonwebtoken.io.Serializer using java.util.ServiceLoader. Ensure you include a backing implementation .jar in the classpath, for example, jjwt-impl.jar, or your own .jar for custom implementations

but this works:

```
    implementation("io.jsonwebtoken:jjwt-api:0.11.2")
    runtimeOnly("io.jsonwebtoken:jjwt-impl:0.11.2")
    runtimeOnly("io.jsonwebtoken:jjwt-jackson:0.11.2")
```

**Comment by lhazlewood** [comment] 2023-03-18 20:36
I've created #773 to address the misleading exception message (thanks @darioseidl !), but as of 0.11.0 and later, the installation instructions and examples all show that one of Jackson, Gson, or org.json dependencies is a required (uncommented) dependency:

https://github.com/jwtk/jjwt/tree/0.11.0#install

It's not clear to me why people were missing the required dependencies in their build configuration.  I'd be happy to update the docs if there's any feedback on how this could be made clearer.

**Comment by phil294** [comment] 2023-07-28 08:18
Adding `jjwt-jackson` did **not** get rid of this error for me, neither with 0.11.2 nor 0.11.5. Any idea what else I can do? Even worse, it used to work until recently, I only reinstalled the dependencies without changes to pom.xml :/

**Comment by phil294** [comment] 2023-07-28 08:28
> Adding `jjwt-jackson` did **not** get rid of this error for me, neither with 0.11.2 nor 0.11.5. Any idea what else I can do? Even worse, it used to work until recently, I only reinstalled the dependencies without changes to pom.xml :/

Nevermind, it seems that our deployment pipeline was broken

**Comment by cnGitHubBruno** [comment] 2025-02-04 16:14
> I've created [#773](https://github.com/jwtk/jjwt/issues/773) to address the misleading exception message (thanks [@darioseidl](https://github.com/darioseidl) !), but as of 0.11.0 and later, the installation instructions and examples all show that one of Jackson, Gson, or org.json dependencies is a required (uncommented) dependency:
> 
> https://github.com/jwtk/jjwt/tree/0.11.0#install
> 
> It's not clear to me why people were missing the required dependencies in their build configuration. I'd be happy to update the docs if there's any feedback on how this could be made clearer.

Not sure if this helps, but I am using 0.11.5 with the following maven dependencies.   I see the file in the jjwt-jackson that implements jjwt-api but I still get the "Unable to find an implementation for interface io.jsonwebtoken.io.Deserializer using java.util.ServiceLoader" error message.

`    <dependency>
      <groupId>io.jsonwebtoken</groupId>
      <artifactId>jjwt-api</artifactId>
      <version>${jjwt.version}</version>
    </dependency>
    <dependency>
      <groupId>io.jsonwebtoken</groupId>
      <artifactId>jjwt-impl</artifactId>
      <version>${jjwt.version}</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>io.jsonwebtoken</groupId>
      <artifactId>jjwt-jackson</artifactId>
      <version>${jjwt.version}</version>
      <scope>runtime</scope>
    </dependency>
`

I will try upgrading to 0.12.6 to see if that fixes anything... but it seems very strange that it is failing to find the implementation.  I am also using a fat jar.
