### ISSUE TITLE
Set claims can erase other claim setters in JwtBuilder

### ISSUE THREAD

**Issue by bhowell2** [jwtk/jjwt#70] opened 2015-12-02 05:21 UTC
The documentation does not state it, but in the code, you can see that any call to `setClaims(...)` in `JwtBuilder` will overwrite any convenience claims that were written  (e.g., `setIssuer()`, `setAudience()`, etc.).  This is somewhat inconsistent, since `audience`, `issuer`, etc., are claims (registered) as well. It may be more clear to just leave out `setIssuer()`, `setAudience()`, and company, rather than allowing them in the builder, even if they are convenient there.  What is the expected behavior when you set the `audience` in the `claims` **and** in the `builder`? It now depends on the order in which you set them:

1. If you set the audience and such (on the `JwtBuilder`) before you set the claims they will be erased, but if you set the audience AFTER you set the claims they will be set.
2. If you set the audience in the `Claims` and then set it again in the `JwtBuilder` (AFTER calling `setClaims`), the audience will be overwritten by the one set in `JwtBuilder`.

I don't think people should be setting them in both places very often and if they do it's almost always going to be by mistake, but I still think it would be more clear to remove the convenience methods for setting default claims out of the builder. Or, remove/rename `setClaims` and change it to `addClaims` (add claims won't overwrite claims now, but just add onto it if it already exist).

**Comment by lhazlewood** [comment] 2015-12-02 19:11
Closing as a duplicate of #66.

**Closed by lhazlewood** 2015-12-02 19:11 UTC
