### ISSUE TITLE
SecretKey algorithm did not equal one of the three required JCA

### ISSUE THREAD

**Issue by rodmaz** [jwtk/jjwt#381] opened 2018-08-13 21:33 UTC
Hi there,

We have struggled for over 2 hours to get this library to work (for a such a simple task (JWT) as to generate a simple JWT). Not a good start! 

We end up figuring out the final problem to be this exception:

`SecretKey algorithm did not equal one of the three required JCA algorithm names of HmacSHA256, HmacSHA384, or HmacSHA512.`

The collection `PREFERRED_HMAC_ALGS` has `jcaName`s internally as `HmacSHA256` etc. **using camelcase**. However when we generate a key using the library:

`val key = Keys.secretKeyFor(SignatureAlgorithm.HS256)`

The internal jcaName generated in the key is `HMACSHA256`, **all uppercase**. The method `SignatureAlgorithm()` throws an exception [here] https://github.com/jwtk/jjwt/blob/1839ebf5e8004336b018c9923bd09ee7deebdf39/api/src/main/java/io/jsonwebtoken/SignatureAlgorithm.java#L560

Are we doing something wrong? It can't be this library has such a stupid string comparison bug and nobody else has notice it?!

We are using the version `0.9.0` from `master`.

**Comment by lhazlewood** [comment] 2018-08-13 22:05
`0.9.0` does not have the logic you describe.

I understand why you'd be frustrated after two hours, but we're here to help, please try not to be too confrontational.  The entire codebase has 100% code coverage, so we try extremely hard to ensure that everything works perfectly, but code coverage assertions even has its faults.

The internal JCA provider should have identical names on both creation and key.getAlgorithm() results.  Could you please tell us if you're running standard JDK, Android or BouncyCastle?

**Comment by lhazlewood** [comment] 2018-08-13 22:32
Even with the test the JCA name is less important than the key length, so I'll use this ticket to change the assertion from a name to a key length.  We'll get a quick 0.10.3 release out asap to address this.

Even so, what version of the JDK are you using?

**Comment by rodmaz** [comment] 2018-08-13 22:54
Hi Les,

Thanks for your prompt feedback. Our engineer in directly charge of this actually already left for today. We found this issue by actually stepping into the class SignatureAlgorithm and the string comparison fails, as we described.
We are actually running this on Android and the project is written in Kotlin. Perhaps we have an issue here. I will let you know more details tomorrow.

Honestly, we also found very strange that a library so popular has such a stupid issue, but we can actually reproduce it at least on Android.

TTY tomorrow.

Thanks again!

**Comment by rodmaz** [comment] 2018-08-13 23:00
Anyway, I agree that directly string comparison (case-sensitive) is not the best solution. On Android we may have it in camelcase, as it seems to be the case. Are we the first ones to use it on Android?  🤔

**Comment by lhazlewood** [comment] 2018-08-13 23:01
Hi @rodmaz 

Thanks for letting me know.

It's not a stupid issue in JJWT however - the release where you're seeing the issue is only a week or so old.  I have had feedback from Android devs that are using JJWT 10.x in prod - they probably just haven't come across this particular edge case based on how they use JJWT.

What *is* stupid IMO is that the Android JVM has an internal discrepancy on how it names JCA algorithms.  This problem doesn't exist on any JDK that we test on (7, 8, 9 and 10).

Our build system tests on all of these JDKs, but, to the best of my knowledge, there is no Travis CI ability to run *both* JDK and Android VMs in a single build, otherwise we would have caught this (IMO bug) that is Android's fault.

If anyone knows how to add Android VMs into our existing Travis setup, I'd love to know how.  Otherwise, we try really hard to test things based on Android's public APIs and cursory testing from the Android community.  I'd love some extra Android CI help here if possible.

**Comment by lhazlewood** [comment] 2018-08-13 23:03
P.S. I'm cutting a 0.10.3 release tonight so you shouldn't see this issue (since the assertion will be on key lengths only).  Your engineer should be able to try tomorrow with the new 0.10.3 release and have it work out.  If not, don't worry - I'm happy to help and we'll get you guys up and running asap. :)

**Comment by rodmaz** [comment] 2018-08-13 23:05
@lhazlewood Thanks Les! We were about to fork it and do a pull-request tomorrow. We will analyse and let you know.

**Comment by rodmaz** [comment] 2018-08-13 23:06
We also saw some (in fact many) situations in which the JJWT actually freezes on Android when we called the `compact()` method. This may be yet another issue w/ Android.

**Comment by lhazlewood** [comment] 2018-08-13 23:18
@rodmaz any information on those freezes would be greatly appreciated.  There are a ton of people using JJWT in Android, so if we can fill in any remaining gaps, all the better.

**Comment by lhazlewood** [comment] 2018-08-14 00:36
Released with 0.10.3 - please allow 30 min or so to propagate to Maven Central.

**Comment by rodmaz** [comment] 2018-08-14 13:39
@lhazlewood This is what we see on Android 5.1 (old) and Android 8 (Samsung). Even when using Android emulator on macOS the problem exists with camelcase.
![screen shot 2018-08-14 at 10 21 11](https://user-images.githubusercontent.com/55300/44095080-43569778-9fae-11e8-945c-6e801937c10f.png)

**Comment by rodmaz** [comment] 2018-08-14 13:57
@lhazlewood We just tested version 0.10.3 and it turns out the problem persists. The class `SignatureAlgorithm` checks against the `jcaName` in other places. Now the problem occurs in another line in the same class.
See this screenshot.
![screen shot 2018-08-14 at 10 51 45](https://user-images.githubusercontent.com/55300/44096062-b67fa472-9fb0-11e8-8cb4-d71fd6db3f45.png)

**Comment by lhazlewood** [comment] 2018-08-14 14:59
Thanks for the follow up - I really appreciate it.

In my haste to get you up and running, I only fixed what was reported.  I'll do a full usage search of `jcaName` and ensure comparisons are case-insensitive.  The check still should be there to prevent using invalid keys for a different algorithm for which it was intended, but clearly Android likes to change standard, documented JCA name casing at their whim.

I'll fix this asap and get 0.10.4 out.  Sorry for the trouble.

**Comment by lhazlewood** [comment] 2018-08-14 15:06
P.S.  Does anyone know how to test this in CI?  We put in a great deal of work to put in 100% code coverage on every build specifically to catch these types of 'gotchas', but that's not guaranteed unless Android is part of the CI runs.

As an example, I found this Android project on GH, and looked at its travis config:

![image](https://user-images.githubusercontent.com/121180/44099927-c09b15ee-9fb1-11e8-8033-bfff70a81e68.png)

The `language` is `android` as expected, but it says the jdk is `oraclejdk8`.

If that's the case (using Oracle JDK 8), and all JJWT Oracle JDK 8 builds pass without exposing this problem, wouldn't this problem stay hidden and not be resolved with TravisCI?

Or does `oraclejdk8` with language `android` not really mean Oracle's JDK but the Android SDK that is compatible with Oracle JDK 8 language features.  Does anyone know?

**Comment by rodmaz** [comment] 2018-08-14 15:10
@lhazlewood Thanks! 

P.S. We do not use TravisCI but you can also check out [this post](https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4).

**Comment by lhazlewood** [comment] 2018-08-14 15:13
@rodmaz I read the article but the examples there also show using `oraclejdk8`.  So my question still stands. ;)

**Comment by lhazlewood** [comment] 2018-08-14 15:26
Wow - from that document, nestled in one little innocuous line:

> Note: Standard names are not case-sensitive.

Well, this is a good confirmation of the `.equalsIgnoreCase` change~

**Comment by lhazlewood** [comment] 2018-08-14 16:38
Released in 0.10.4.  Please allow 30 minutes to propagate to Maven Central.

**Comment by rpanak-generalbytes** [comment] 2019-11-11 18:48
@lhazlewood I've encountered a similar bug with loading the key in a PKCS 12 keystore. The algorithm name of the secret key gets for some reason (guess it's because it's mandated by the PKCS12 spec) converted to an OID (e.g. HmacSHA512 is 1.2.840.113549.2.11; see http://www.oid-info.com/cgi-bin/display?oid=1.2.840.113549.2.11&action=display). After loading the key, the algorithm identifier stays in the OID format and thus your check fails. I've solved this problem by switching to a different keystore format (JCEKS in my case). Couldn't make the PKCS12 one work. The sad thing is that PKCS12 is the default since some relatively recent Java release (9 I guess; my problem was on JDK11).

**Comment by lhazlewood** [comment] 2019-11-12 15:28
@rpanak-generalbytes can you please help me understand how/where JJWT is involved in what you're seeing?  JJWT doesn't load keys from keystores.  Do you have any example code that demonstrates a problem?  Thanks!

**Comment by rpanak-generalbytes** [comment] 2019-11-20 11:39
Sure. You are right, JJWT is not involved with keystores. However, that is just an information about how to reproduce the problem (to be precise, how to unwillingly create a valid `SecretKey` that is not usable with JJWT). 

The problem itself is that you can have a valid `SecretKey` for HmacSHA512, but the string returned by calling `SecretKey#getAlgorithm()` will be the OID (1.2.840.113549.2.11), not the actual string `"HmacSHA512"`. Your key validity check (`SignatureAlgorithm#assertValid`) will thus fail (the OID is not equal to any of the expected algorithm names). I guess SunJCE and other crypto providers do some mapping internally to a canonical name and thus the key works (take a look at [this source file](http://hg.openjdk.java.net/jdk/jdk11/file/tip/src/java.base/share/classes/com/sun/crypto/provider/SunJCE.java), 90 % of the content is OID mapping). 

Also, I have found that `SignatureAlgorithm#forSigningKey` finds the algorithm based on the key length. This is incorrect in my opinion. If I have a 512-bit key for HmacSHA256 (which is a valid key length), the algorithm returns the first HMAC for which the key length is enough, i.e.HmacSHA512. I think that is confusing behavior since the algorithm information is present with the key. I'd understand this alg matching heuristic if the key was given as raw bytes (thus no alg information). This is, however, an unrelated problem so I can create a new issue for this if you'd like. In case you'd be fixing this, the OID matching problem will be present as well.

**Comment by fibsifan** [comment] 2020-04-23 11:39
This is closed now, but I too am experiencing issues with a HmacSha512 Key loaded from a PKCS 12. I'm unsure, whether this is an Issue with the JDK I'm using (OpenJDK in this case) or a problem with jjwt.

The following example might illustrate the problem:

`
package de.jball.crypt.playground;

import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.SignatureAlgorithm;
import io.jsonwebtoken.security.Keys;

import java.io.File;
import java.security.Key;
import java.security.KeyStore;
import java.security.cert.Certificate;

public class Main {
	public static void main(String[] args) throws Exception {
		KeyStore pkcs12 = KeyStore.getInstance("pkcs12");
		File tempFile = File.createTempFile("keystore", "pkcs12");
		pkcs12.load(null, "keystorepassword".toCharArray());

		Key key = Keys.secretKeyFor(SignatureAlgorithm.HS512);
		pkcs12.setKeyEntry("testkey", key, "keypassword".toCharArray(), new Certificate[0]);
		key = pkcs12.getKey("testkey", "keypassword".toCharArray());
		System.out.println(Jwts.builder().signWith(key).setSubject("123").compact());
	}
}
`

**Comment by rpanak-generalbytes** [comment] 2020-04-23 12:25
I think `SignatureAlgorithm#assertValid` is still behaving incorrectly. The issue should be reopened.

**Comment by fibsifan** [comment] 2020-04-23 12:55
Created a Test Project with the given code example, which can be used to reproduce the issue.  Could reproduce with OpenJDK11 as well.

Looking at [Java Security Standard Algorithm Names] though, I can't find the String '1.2.840.113549.2.11' anywhere in the document. I would have expected the KeyStore to load the key with the Standard Algorithm name. I might be overlooking something though in the [JCA Reference], which would indicate this behaviour.

[Java Security Standard Algorithm Names]: https://docs.oracle.com/en/java/javase/11/docs/specs/security/standard-names.html
[JCA Reference]: https://docs.oracle.com/javase/8/docs/technotes/guides/security/crypto/CryptoSpec.html#AppA

**Comment by fibsifan** [comment] 2020-04-24 13:42
Since the [corresponding bug report at OpenJDK](https://bugs.openjdk.java.net/browse/JDK-8243551) seems to be accepted _and_ we have a workaround, IMHO this issue can stay closed.

**Comment by lhazlewood** [comment] 2020-04-24 16:48
The alternative is to remove these lines from the assertion check entirely:

https://github.com/jwtk/jjwt/blob/c09deaa5f31fb7b3a8184daec4228269942c77a4/api/src/main/java/io/jsonwebtoken/SignatureAlgorithm.java#L353-L359

But I'm a little hesitant to do that: removing those lines *could* still allow keys that fail when calling `mac.init(key)` if the algorithm name isn't valid.

The safest implementation change would be to remove those lines and then actually perform a test mac calculation, e.g.

```java
private void assertValidHmac(Key key) {
    try {
        Mac mac = Mac.getInstance(this.jcaName);
        mac.init(key);
        mac.doFinal(dummyData);
    catch (IllegalStateException ise) {
        throw new InvalidKeyException("whatever", ise);
    }
}
```

The problem with this approach is that it could be a performance hit due to the extra non-essential calculation.  We'd have to ensure that it is used in a calculated fashion and it might be more effort than it's worth, especially with the workaround that @fibsifan posted.

Thoughts?

**Comment by rpanak-generalbytes** [comment] 2020-04-25 02:04
@lhazlewood I think this is a no-brainer. The safest implementation is to accept the proper aliases (OIDs) as well as the current algorithm names (they're both just alternative names for the same thing). I don't see any downside (correct me if I'm wrong). Easy to implement as well, just add three more cases into the appropriate if statement. The OIDs can be Googled, or found [here](http://oid-info.com/get/1.2.840.113549.2) or  [the JDKs sources link I've already posted before](http://hg.openjdk.java.net/jdk/jdk11/file/tip/src/java.base/share/classes/com/sun/crypto/provider/SunJCE.java).
 Definitely don't go the test Mac route, you listed the cons yourself. The same goes for just removing the checks, there's no need to remove them.

@fibsifan Open JDK bug is a long way from fixed :). In the meantime, we're left to deal with the present problem.

**Comment by lhazlewood** [comment] 2020-04-26 19:25
Adding the OIDs to the check is easy enough - thanks for suggesting the solution!  Reopening so we can address it in a future release.

**Comment by lhazlewood** [comment] 2020-04-26 19:25
Actually, closing this (since it is tied to the 0.10.4 release) and opening a new issue to track that work.

**Closed by lhazlewood** 2020-04-26 19:25 UTC

**Comment by lhazlewood** [comment] 2020-04-26 19:30
OIDs will be added to the validation check via https://github.com/jwtk/jjwt/issues/588
