### ISSUE TITLE
Inexistent dependency required when use Spring Boot 3

### ISSUE THREAD

**Issue by yhojann-cl** [jwtk/jjwt#748] opened 2022-07-14 16:03 UTC
When use Spring boot and try generate a WJT says:

```
2022-07-14T11:54:55.706-04:00 ERROR 81466 --- [0.1-9001-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter] with root cause

java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
        at io.jsonwebtoken.impl.Base64Codec.encode(Base64Codec.java:21) ~[jjwt-0.9.1.jar:0.9.1]
        at io.jsonwebtoken.impl.Base64UrlCodec.encode(Base64UrlCodec.java:22) ~[jjwt-0.9.1.jar:0.9.1]
        at io.jsonwebtoken.impl.DefaultJwtBuilder.base64UrlEncode(DefaultJwtBuilder.java:349) ~[jjwt-0.9.1.jar:0.9.1]
        at io.jsonwebtoken.impl.DefaultJwtBuilder.compact(DefaultJwtBuilder.java:295) ~[jjwt-0.9.1.jar:0.9.1]
        at com.example.Test.test(Test.java:131) ~[main/:na]
...
```

My code is:

```java
public String createJws(SessionDTO sessionDTO) {
    String jws = Jwts.builder()
        .setIssuer("Example")
        .setSubject("session")
        .claim("session-uuid", sessionDTO.getUuid().toString())
        .setIssuedAt(Date.from(sessionDTO.getCreatedAt()))
        .setExpiration(Date.from(sessionDTO.getExpire()))
        .signWith(
            SignatureAlgorithm.HS256,
            jwtSecret.getBytes()
        )
        .compact(); // Line 131
    return jws;
}
```

Enviroment: Spring Boot 3, OpenJDK 17 and Ubuntu 22.04 LTS.

**Comment by bdemers** [comment] 2022-07-14 17:23
@yhojann-cl can you try with the latest version of JJWT?
See: https://github.com/jwtk/jjwt#installation

**Comment by bdemers** [comment] 2022-07-14 20:27
I'm not sure I'm following, your dependency tree lists: `com.auth0:java-jwt:4.0.0`  (I don't see `io.jsonwebtoken` in that list)
and your original exception shows version jjwt-0.9.1 instead of the latest: `0.11.5`
See these instructions if you need help upgrading: https://github.com/jwtk/jjwt#install-jdk-gradle

Can you double check you grabbed the output from the correct project?

**Comment by linghengqian** [comment] 2022-08-06 04:11
I can't reproduce this issue on Spring Boot OSS 3.0.0-M4.  If you can't provide a reproducible example, I think this issue should be marked as invalid.

**Comment by yhojann-cl** [comment] 2022-08-06 18:07
I found the problem, are the main instructions in `readme.md`.

I try using the gradle example for main readme.md of repository but does not work, i use the main repository:

```
dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'

	compile 'io.jsonwebtoken:jjwt-api:0.11.5'
        runtime 'io.jsonwebtoken:jjwt-impl:0.11.5',
        // Uncomment the next line if you want to use RSASSA-PSS (PS256, PS384, PS512) algorithms:
        //'org.bouncycastle:bcprov-jdk15on:1.70',
        'io.jsonwebtoken:jjwt-jackson:0.11.5' // or 'io.jsonwebtoken:jjwt-gson:0.11.5' for gson
}
```

Says:

```
$ ./gradlew bootRun

FAILURE: Build failed with an exception.

* Where:
Build file '/home/whk/Descargas/Spring jwt/project/build.gradle' line: 21

* What went wrong:
A problem occurred evaluating root project 'demo'.
> Could not find method compile() for arguments [io.jsonwebtoken:jjwt-api:0.11.5] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 318ms
```

but i found the main mvn repository in https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt. I made a automatic script for this `poc.sh` using the main implementation `implementation 'io.jsonwebtoken:jjwt:0.9.1'`:

```bash
#!/bin/bash

# Download project
wget -O project.zip 'https://start.spring.io/starter.zip?type=gradle-project&language=java&bootVersion=3.0.0-SNAPSHOT&baseDir=project&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&packaging=jar&javaVersion=17&dependencies=web';

# Uncompress
unzip project.zip && rm -f project.zip;

# Project settings
echo "
plugins {
	id 'org.springframework.boot' version '3.0.0-SNAPSHOT'
	id 'io.spring.dependency-management' version '1.0.12.RELEASE'
	id 'java'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

repositories {
	mavenCentral()
	maven { url 'https://repo.spring.io/milestone' }
	maven { url 'https://repo.spring.io/snapshot' }
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'

	implementation 'io.jsonwebtoken:jjwt:0.9.1'
}

tasks.named('test') {
	useJUnitPlatform()
}

" > ./project/build.gradle;

# Main controller
echo '
package com.example.demo;

import java.util.Date;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.ResponseEntity;
import org.springframework.http.HttpStatus;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.SignatureAlgorithm;


@RestController
public class MainController {

    @GetMapping("/")
    public ResponseEntity<String> main() {
        String secret = "00000000-0000-0000-0000-000000000000";
        String jws = Jwts.builder()
            .setIssuer("Example")
            .setSubject("example")
            .claim("example", "example value")
            .setIssuedAt(new Date())
            .setExpiration(new Date())
            .signWith(
                SignatureAlgorithm.HS256,
                secret.getBytes()
            )
            .compact();
        return new ResponseEntity<>(jws, HttpStatus.OK);
    }
}

' > ./project/src/main/java/com/example/demo/MainController.java;

# Run project
./project/gradlew bootRun
```

The results when call main controller from `http://127.0.0.1:8080/`:

```
2022-08-06T13:56:25.780-04:00 ERROR 23898 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter] with root cause

java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
        at io.jsonwebtoken.impl.Base64Codec.encode(Base64Codec.java:21) ~[jjwt-0.9.1.jar:0.9.1]
...
```

But now use the maven website instructions for gradle:

```
dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'

	implementation group: 'io.jsonwebtoken', name: 'jjwt-api', version: '0.11.5'
	runtimeOnly group: 'io.jsonwebtoken', name: 'jjwt-impl', version: '0.11.5'
	runtimeOnly group: 'io.jsonwebtoken', name: 'jjwt-jackson', version: '0.11.5'
}
```

And works fine. You need updade the instructions for gradle?

**Comment by lhazlewood** [comment] 2022-08-07 01:50
AFAICT, the instructions are fine.

The problem is because there is something in your project - either your configuration, or another third party that depends on JJWT - that depends on JJWT 0.9.1, and that is conflicting with your configured `0.11.5`:

> at io.jsonwebtoken.impl.Base64Codec.encode(Base64Codec.java:21) **~[jjwt-0.9.1.jar:0.9.1]**

You will need to run a dependency tree report and see who or what is pulling in that old `0.9.1` version.  JJWT is a popular library, so something in Spring Boot or one of its transitive dependencies might be importing the older version.  Please report back what is importing it when you find it - thanks!

**Comment by lhazlewood** [comment] 2022-08-07 01:51
Found this, hope it helps: https://docs.gradle.org/current/userguide/viewing_debugging_dependencies.html

**Comment by Mikhail2048** [comment] 2023-05-20 08:39
Guys, there is nothing bad in spring-boot 3.

Spring-boot 3 simply requires jdk 17 as a baseline. `jaxb-api` and a lot of other Java EE specs was remove in java 9. The problem is that in your `pom.xml`  you do not have `jaxb-api`, either explicitly defined or grabbed via transitive dependency. So we all get the JVM `NoClassDefFoundError` error at runtime.

So guys @lhazlewood @bdemers please, just add the missing dependency, or I can provide the PR if you want. Otherwise everyone who works on jdk 9 and above would have to include `jaxb-api` himself.

**Comment by lhazlewood** [comment] 2023-05-20 20:35
@Mikhail2048 this is simply not true - JJWT doesn't require a JAXB dependency at all.

JJWT correctly builds and runs - with all 1000+ integration tests - on JDK 7 all the way up to and including **JDK 18**.  At no point anywhere in our build configuration do we reference or depend upon the JAXB APIs or the `jaxb-api` .jar.  Here is the build proof, per JDK, for the latest `master` build:

https://github.com/jwtk/jjwt/actions/runs/5028363322

This seems to clearly demonstrate that JAXB isn't required.  Maybe it's a problem with Spring Boot 3 on JDK 17?  This doesn't have anything to do with JJWT's requirements or dependencies, so I don't see how we'd modify the JJWT project.

Do you have a sample project that demonstrates the problem?

**Comment by Mikhail2048** [comment] 2023-05-21 07:01
@lhazlewood I understand the missconception between us. As you pointed here: https://github.com/jwtk/jjwt/issues/783,
` 0.9.1` is not the latest version of library (I am sorry again). Check this line of code: https://github.com/jwtk/jjwt/blob/0.9.1/src/main/java/io/jsonwebtoken/impl/Base64Codec.java#L21
It is clearly the `javax-api` jar class,, it is in 0.9.1 tag. And when I left a comment I was really talking about `0.9.1` version. I hope @lhazlewood you understand my concern now. And in the original version in this issue - it also was 0.9.1, check the comments above :)

**Comment by lhazlewood** [comment] 2023-08-11 20:18
@Mikhail2048 thank you for the clarification, but JJWT 0.9.1 isn't supported any longer - it's a 7+-year old release.  There is no point in adding back in the `jaxb` dependency to JJWT.  If they're experiencing this problem, the correct solution is to upgrade to JJWT `0.11.5` or later.

FWIW, we have added back in the 'single dependency' artifact to Maven Central as a convenience for those that are ok with Jackson being the JSON processor with a85815351806a35461d951d41fcc3c2ce14b7904.  That will be available in the next release (e.g. `0.12.0`).

I'm closing this issue since 0.9.x is no longer supported.

**Closed by lhazlewood** 2023-08-11 20:18 UTC
