### ISSUE TITLE
Windows RSAPrivateKey (MSCAPI)

### ISSUE THREAD

**Issue by x2on** [jwtk/jjwt#160] opened 2016-09-06 11:31 UTC
Hi,

im loading a RSAPrivateKey on Windows with the following code:

```java
KeyStore ks = KeyStore.getInstance("Windows-MY");
ks.load(null, null);
RSAPrivateKey privateKey = ks.getKey("someKeyAlias", null);
```

But then i get the following exception:
```java
Exception in thread "main" java.lang.IllegalArgumentException: RSA signatures must be computed using an RSAPrivateKey.  
The specified key of type sun.security.mscapi.RSAPrivateKey is not an RSAPrivateKey.
	at io.jsonwebtoken.impl.crypto.RsaSigner.<init>(RsaSigner.java:34)
	at io.jsonwebtoken.impl.crypto.DefaultSignerFactory.createSigner(DefaultSignerFactory.java:43)
	at io.jsonwebtoken.impl.crypto.DefaultJwtSigner.<init>(DefaultJwtSigner.java:37)
	at io.jsonwebtoken.impl.crypto.DefaultJwtSigner.<init>(DefaultJwtSigner.java:32)
	at io.jsonwebtoken.impl.DefaultJwtBuilder.createSigner(DefaultJwtBuilder.java:339)
	at io.jsonwebtoken.impl.DefaultJwtBuilder.compact(DefaultJwtBuilder.java:321)
```

Any idea why this is not compatible?

**Comment by bhowell2** [comment] 2016-09-06 17:57
Is this an RSA key generated with MSCAPI? Did you store this generated key in the Java Keystore? There are some articles out there that describe how to load your keys into a Java Keystore.

**Comment by bhowell2** [comment] 2016-09-06 19:02
I've also assumed in the response above that you didn't actually use `null` in the `load(null, null)` call above - i figured you would get an error thrown way before about that.

**Comment by x2on** [comment] 2016-09-07 06:59
Hi,
im loading the RSAPrivateKey from the Windows Certificate store with the code above.
It works and i get a valid key from the certificate store.
Then i use the following code:

```java
String payload = Jwts.builder()
.setPayload("somePayload")
.signWith(SignatureAlgorithm.RS256, privateKey)
.compact();
```

And this call throws the error above.

**Comment by bhowell2** [comment] 2016-09-07 14:28
I know you're saying it loads, but this part: `The specified key of type sun.security.mscapi.RSAPrivateKey is not an RSAPrivateKey.` suggests that the issue is related to the key. I then looked into what RSAPrivateKey it was expecting (see below) and it is a `java.security.interfaces.RSAPrivateKey`, but `sun.security.mscapi.RSAPrivateKey` implements `java.security.interfaces.PrivateKey` and therefore the `instanceOf` check in the 0.6.0 tag release (listed below) does not check out. I don't think the current master would work either, since it checks for `PrivateKey` AND `RSAKey` (from `java.security.interfaces`). Get your keys out of the store and put them in a Java Keystore (or just generate a keystore with RSA keys from java keytool).

0.6.0 RsaSigner:
```java
    public RsaSigner(SignatureAlgorithm alg, Key key) {
        super(alg, key);
        if (!(key instanceof RSAPrivateKey)) {
            String msg = "RSA signatures must be computed using an RSAPrivateKey.  The specified key of type " +
                         key.getClass().getName() + " is not an RSAPrivateKey.";
            throw new IllegalArgumentException(msg);
        }
    }
```

**Comment by lhazlewood** [comment] 2016-09-12 17:45
The check was changed from `RSAPrivateKey` because Android doesn't implement that interface - it implements both `RSAKey` and `PrivateKey`, and I believe all JCA-compatible implementations should do this.  `sun.security.mscapi.RSAPrivateKey` does not appear to be JCA-compatible; when working with Java crypto, please always reference interfaces, not concrete implementation classes.

**Comment by lhazlewood** [comment] 2016-09-12 17:49
P.S. I'm going to close this as I don't think this is something relevant to JJWT - we will only program to standard JCA API interfaces, not implementation classes.  I think you'll need to find a way to represent the `sun.security.mscapi.RSAPrivateKey` instance as something that implements both `java.security.interfaces.RSAKey` and `java.security.PrivateKey`.

Keys in a Java KeyStore meet this criteria, but if you don't want to go through that you could implement your own 'wrapper' class:  create a class that implements both interfaces and each method implementation delegates to the `sun.security.mscapi.RSAPrivateKey` instance.

**Closed by lhazlewood** 2016-09-12 17:49 UTC

**Comment by x2on** [comment] 2016-09-18 10:50
Yeah thats true! Thought that `sun.security.mscapi.RSAPrivateKey` is compatible, but the interface is different...

Thanks for your investigation.

**Comment by epot** [comment] 2017-01-12 08:21
@lhazlewood it looks like `sun.security.mscapi.RSAPrivateKey` is not available since it is in a private package. Any idea on how what you suggest with this limitation ?

**Comment by totszwai** [comment] 2017-10-23 17:16
How do you get this to work?? I'm facing the same problem.
`RSA signatures must be computed using an RSA PrivateKey.  The specified key of type sun.security.mscapi.RSAPrivateKey is not an RSA PrivateKey.`

**Comment by oddbjornkvalsund** [comment] 2018-07-04 07:31
For others coming here with the same problem, I solved this by subclassing `io.jsonwebtoken.impl.DefaultJwtBuilder` and supplying my own `io.jsonwebtoken.impl.crypto.Signer`:

```
final DefaultJwtBuilder jwtBuilder = new DefaultJwtBuilder() {
    @Override
    protected JwtSigner createSigner(SignatureAlgorithm alg, Key key) {
        final SignerFactory signerFactory = new DefaultSignerFactory() {
            @Override
            public Signer createSigner(SignatureAlgorithm alg, Key key) {
                return bytes -> {
                    try {
                        final Signature sig = Signature.getInstance(alg.getJcaName());
                        sig.initSign((PrivateKey) key);
                        sig.update(bytes);
                        logger.info("Signed data of length {} with key: {}", bytes.length, key);
                        return sig.sign();
                    } catch (Exception e) {
                        throw new RuntimeException("Unable to sign JWT!", e);
                    }
                };
            }
        };
        return new DefaultJwtSigner(signerFactory, alg, key);
    }
};
```

This instance of `DefaultJwtBuilder` can then be used instead of `Jwts.builder()`. The passed-in `key` in my case is an instance of `sun.security.mscapi.RSAPrivateKey`.

Example use: 
```
final String signedJwt = jwtBuilder
                .setClaims(claims)
                .setIssuer(myIssuer)
                .setAudience(myAudience)
                .setExpiration(new Date(System.currentTimeMillis() + 60_000))
                .signWith(SignatureAlgorithm.RS256, mySunMSCAPIKey)
                .compact();
```


Works like a charm in my case, but YMMV.

**Comment by Ulterior** [comment] 2020-12-11 20:43
> For others coming here with the same problem, I solved this by subclassing `io.jsonwebtoken.impl.DefaultJwtBuilder` and supplying my own `io.jsonwebtoken.impl.crypto.Signer`:
> 
> ```
> final DefaultJwtBuilder jwtBuilder = new DefaultJwtBuilder() {
>     @Override
>     protected JwtSigner createSigner(SignatureAlgorithm alg, Key key) {
>         final SignerFactory signerFactory = new DefaultSignerFactory() {
>             @Override
>             public Signer createSigner(SignatureAlgorithm alg, Key key) {
>                 return bytes -> {
>                     try {
>                         final Signature sig = Signature.getInstance(alg.getJcaName());
>                         sig.initSign((PrivateKey) key);
>                         sig.update(bytes);
>                         logger.info("Signed data of length {} with key: {}", bytes.length, key);
>                         return sig.sign();
>                     } catch (Exception e) {
>                         throw new RuntimeException("Unable to sign JWT!", e);
>                     }
>                 };
>             }
>         };
>         return new DefaultJwtSigner(signerFactory, alg, key);
>     }
> };
> ```
> 
> This instance of `DefaultJwtBuilder` can then be used instead of `Jwts.builder()`. The passed-in `key` in my case is an instance of `sun.security.mscapi.RSAPrivateKey`.
> 
> Example use:
> 
> ```
> final String signedJwt = jwtBuilder
>                 .setClaims(claims)
>                 .setIssuer(myIssuer)
>                 .setAudience(myAudience)
>                 .setExpiration(new Date(System.currentTimeMillis() + 60_000))
>                 .signWith(SignatureAlgorithm.RS256, mySunMSCAPIKey)
>                 .compact();
> ```
> 
> Works like a charm in my case, but YMMV.

Works like a charm in my case too
